### ISSUE TITLE
Duppy instantly crashes

### ISSUE THREAD

**Issue by inomfood** [ZonD80/duppy#6] opened 2020-06-12 23:40 UTC
While attempting to open duppy, it instantly crashes. The app is installed from the official website, and Appsync Unified is installed. I am testing on an iPhone XS max on iOS 12.1.1 beta 3 using the Unc0ver jailbreak. I have also tested and gotten the same result on an iPad Pro 2018 with Unc0ver running iOS 13.5. I have attached the cr4shed log output created on my phone during the event.
[cr4shed crash log](https://github.com/ZonD80/duppy/files/4773625/text.txt)

EDIT: looking into it more, this crash does not happen on builds 1.1.4 or earlier. It only takes place on versions newer than 1.1.4.

**Comment by ZonD80** [comment] 2020-06-13 07:19
I can't reproduce this issue, looks like there is an issue with specific app icon that is installed on your device. Can you try to build app from sources and run via xcode with debugger attached?

**Comment by ZonD80** [comment] 2020-06-15 16:32
I will close this issue soon if I will receive no info for debug

**Comment by inomfood** [comment] 2020-06-16 03:20
> I can't reproduce this issue, looks like there is an issue with specific app icon that is installed on your device. Can you try to build app from sources and run via xcode with debugger attached?

I'm sorry for the late response, I am not sure how to do this. I have pretty minimal experience in Xcode.

**Comment by ZonD80** [comment] 2020-06-16 06:15
Some app icon causing this crash I suppose. We need to find which app. You can build app from sources (check readme) and install it via xcode with debugger support

**Comment by ZonD80** [comment] 2020-06-19 20:55
You can reopen it again when you will have new debug info

**Closed by ZonD80** 2020-06-19 20:55 UTC
